// <auto-generated />
using System;
using FinalProject.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinalProject.Migrations
{
    [DbContext(typeof(WebDbContext))]
    partial class WebDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FinalProject.Models.Brand", b =>
                {
                    b.Property<int>("BrandID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BrandID"));

                    b.Property<string>("BrandName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("BrandID");

                    b.ToTable("tb_Brand");

                    b.HasData(
                        new
                        {
                            BrandID = 1,
                            BrandName = "Nike"
                        },
                        new
                        {
                            BrandID = 2,
                            BrandName = "Adidas"
                        },
                        new
                        {
                            BrandID = 3,
                            BrandName = "Uniqlo"
                        },
                        new
                        {
                            BrandID = 4,
                            BrandName = "Zara"
                        },
                        new
                        {
                            BrandID = 5,
                            BrandName = "H&M"
                        });
                });

            modelBuilder.Entity("FinalProject.Models.CartItems", b =>
                {
                    b.Property<int>("CartItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CartItemId"));

                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("CartItemId");

                    b.HasIndex("CartId");

                    b.HasIndex("ProductID");

                    b.ToTable("tb_CartItems");
                });

            modelBuilder.Entity("FinalProject.Models.Carts", b =>
                {
                    b.Property<int>("CartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CartId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.HasKey("CartId");

                    b.HasIndex("CustomerId");

                    b.ToTable("tb_Carts");
                });

            modelBuilder.Entity("FinalProject.Models.Order", b =>
                {
                    b.Property<int>("OrderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderID"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerID")
                        .HasColumnType("int");

                    b.Property<bool>("Delivered")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DeliveryDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Discount")
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrderStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OrderID");

                    b.HasIndex("CustomerID");

                    b.ToTable("tb_Order");

                    b.HasData(
                        new
                        {
                            OrderID = 1,
                            CreatedDate = new DateTime(2026, 4, 17, 0, 46, 35, 686, DateTimeKind.Local).AddTicks(486),
                            CustomerID = 1,
                            Delivered = true,
                            DeliveryDate = new DateTime(2026, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Discount = 0,
                            OrderDate = new DateTime(2026, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderStatus = "Completed",
                            PaymentStatus = "Paid",
                            TotalPrice = 1250000m
                        },
                        new
                        {
                            OrderID = 2,
                            CreatedDate = new DateTime(2026, 4, 17, 0, 46, 35, 686, DateTimeKind.Local).AddTicks(495),
                            CustomerID = 1,
                            Delivered = true,
                            DeliveryDate = new DateTime(2026, 4, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Discount = 0,
                            OrderDate = new DateTime(2026, 4, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderStatus = "Completed",
                            PaymentStatus = "Paid",
                            TotalPrice = 850000m
                        },
                        new
                        {
                            OrderID = 3,
                            CreatedDate = new DateTime(2026, 4, 17, 0, 46, 35, 686, DateTimeKind.Local).AddTicks(498),
                            CustomerID = 1,
                            Delivered = true,
                            DeliveryDate = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Discount = 0,
                            OrderDate = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderStatus = "Completed",
                            PaymentStatus = "Paid",
                            TotalPrice = 2100000m
                        },
                        new
                        {
                            OrderID = 4,
                            CreatedDate = new DateTime(2026, 4, 17, 0, 46, 35, 686, DateTimeKind.Local).AddTicks(500),
                            CustomerID = 1,
                            Delivered = true,
                            DeliveryDate = new DateTime(2026, 4, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Discount = 0,
                            OrderDate = new DateTime(2026, 4, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderStatus = "Completed",
                            PaymentStatus = "Paid",
                            TotalPrice = 1500000m
                        },
                        new
                        {
                            OrderID = 5,
                            CreatedDate = new DateTime(2026, 4, 17, 0, 46, 35, 686, DateTimeKind.Local).AddTicks(503),
                            CustomerID = 1,
                            Delivered = true,
                            DeliveryDate = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Discount = 0,
                            OrderDate = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderStatus = "Completed",
                            PaymentStatus = "Paid",
                            TotalPrice = 3200000m
                        },
                        new
                        {
                            OrderID = 6,
                            CreatedDate = new DateTime(2026, 4, 17, 0, 46, 35, 686, DateTimeKind.Local).AddTicks(505),
                            CustomerID = 1,
                            Delivered = true,
                            DeliveryDate = new DateTime(2026, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Discount = 0,
                            OrderDate = new DateTime(2026, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderStatus = "Completed",
                            PaymentStatus = "Paid",
                            TotalPrice = 950000m
                        },
                        new
                        {
                            OrderID = 7,
                            CreatedDate = new DateTime(2026, 4, 17, 0, 46, 35, 686, DateTimeKind.Local).AddTicks(507),
                            CustomerID = 1,
                            Delivered = true,
                            DeliveryDate = new DateTime(2026, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Discount = 0,
                            OrderDate = new DateTime(2026, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderStatus = "Completed",
                            PaymentStatus = "Paid",
                            TotalPrice = 1800000m
                        });
                });

            modelBuilder.Entity("FinalProject.Models.OrderDetails", b =>
                {
                    b.Property<int>("OrderDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderDetailId"));

                    b.Property<int?>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int?>("ShopId")
                        .HasColumnType("int");

                    b.HasKey("OrderDetailId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.HasIndex("ShopId");

                    b.ToTable("tb_OrderDetails");

                    b.HasData(
                        new
                        {
                            OrderDetailId = 1,
                            OrderId = 1,
                            Price = 450000m,
                            ProductId = 1,
                            Quantity = 2
                        },
                        new
                        {
                            OrderDetailId = 2,
                            OrderId = 2,
                            Price = 550000m,
                            ProductId = 2,
                            Quantity = 1
                        },
                        new
                        {
                            OrderDetailId = 3,
                            OrderId = 3,
                            Price = 450000m,
                            ProductId = 1,
                            Quantity = 5
                        },
                        new
                        {
                            OrderDetailId = 4,
                            OrderId = 4,
                            Price = 550000m,
                            ProductId = 2,
                            Quantity = 3
                        },
                        new
                        {
                            OrderDetailId = 5,
                            OrderId = 5,
                            Price = 450000m,
                            ProductId = 1,
                            Quantity = 10
                        },
                        new
                        {
                            OrderDetailId = 6,
                            OrderId = 6,
                            Price = 550000m,
                            ProductId = 2,
                            Quantity = 2
                        },
                        new
                        {
                            OrderDetailId = 7,
                            OrderId = 7,
                            Price = 450000m,
                            ProductId = 1,
                            Quantity = 4
                        });
                });

            modelBuilder.Entity("FinalProject.Models.Product", b =>
                {
                    b.Property<int>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductID"));

                    b.Property<int?>("BrandID")
                        .HasColumnType("int");

                    b.Property<int?>("CateID")
                        .HasColumnType("int");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Hot")
                        .HasColumnType("bit");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ListImages")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MetaDescription")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("MetaKeywords")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int?>("PromotionId")
                        .HasColumnType("int");

                    b.Property<decimal>("PromotionPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("SeoTitle")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("ShopID")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("VAT")
                        .HasColumnType("bit");

                    b.Property<int>("ViewCount")
                        .HasColumnType("int");

                    b.HasKey("ProductID");

                    b.HasIndex("BrandID");

                    b.HasIndex("CateID");

                    b.HasIndex("PromotionId");

                    b.HasIndex("ShopID");

                    b.ToTable("tb_Product");

                    b.HasData(
                        new
                        {
                            ProductID = 1,
                            BrandID = 3,
                            CateID = 4,
                            CreatedDate = new DateTime(2026, 3, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Detail = "100% Cotton",
                            Hot = true,
                            Image = "white-shirt.jpg",
                            ListImages = "img1.jpg,img2.jpg",
                            MetaDescription = "shirt",
                            MetaKeywords = "shirt",
                            Price = 450000m,
                            ProductDescription = "Classic fit white oxford shirt",
                            ProductName = "Premium White Oxford Shirt",
                            PromotionPrice = 399000m,
                            Quantity = 100,
                            SeoTitle = "premium-white-oxford-shirt",
                            ShopID = 1,
                            Status = true,
                            VAT = true,
                            ViewCount = 0
                        },
                        new
                        {
                            ProductID = 2,
                            BrandID = 4,
                            CateID = 6,
                            CreatedDate = new DateTime(2026, 3, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Detail = "Chiffon material",
                            Hot = false,
                            Image = "floral-dress.jpg",
                            ListImages = "img3.jpg,img4.jpg",
                            MetaDescription = "dress",
                            MetaKeywords = "dress",
                            Price = 550000m,
                            ProductDescription = "Elegant floral print dress",
                            ProductName = "Floral Summer Maxi Dress",
                            PromotionPrice = 490000m,
                            Quantity = 50,
                            SeoTitle = "floral-summer-maxi-dress",
                            ShopID = 1,
                            Status = true,
                            VAT = true,
                            ViewCount = 0
                        },
                        new
                        {
                            ProductID = 3,
                            BrandID = 2,
                            CateID = 5,
                            CreatedDate = new DateTime(2026, 3, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Detail = "Stretchy fabric",
                            Hot = true,
                            Image = "anh1sanpham.jpg",
                            ListImages = "img5.jpg",
                            MetaDescription = "pants",
                            MetaKeywords = "chinos",
                            Price = 600000m,
                            ProductDescription = "High-quality khaki pants",
                            ProductName = "Slim Fit Navy Chinos",
                            PromotionPrice = 550000m,
                            Quantity = 80,
                            SeoTitle = "slim-fit-navy-chinos",
                            ShopID = 1,
                            Status = true,
                            VAT = true,
                            ViewCount = 0
                        },
                        new
                        {
                            ProductID = 4,
                            BrandID = 5,
                            CateID = 7,
                            CreatedDate = new DateTime(2026, 3, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Detail = "Handmade",
                            Hot = false,
                            Image = "anh2sanpham.jpg",
                            ListImages = "img6.jpg",
                            MetaDescription = "bag",
                            MetaKeywords = "bag",
                            Price = 1200000m,
                            ProductDescription = "Genuine leather bag",
                            ProductName = "Leather Crossbody Bag",
                            PromotionPrice = 990000m,
                            Quantity = 30,
                            SeoTitle = "leather-crossbody-bag",
                            ShopID = 1,
                            Status = true,
                            VAT = true,
                            ViewCount = 0
                        },
                        new
                        {
                            ProductID = 5,
                            BrandID = 1,
                            CateID = 9,
                            CreatedDate = new DateTime(2026, 3, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Detail = "Waterproof 50m",
                            Hot = true,
                            Image = "anh3sanpham.jpg",
                            ListImages = "img7.jpg",
                            MetaDescription = "watch",
                            MetaKeywords = "watch",
                            Price = 3500000m,
                            ProductDescription = "Elegant gold-plated watch",
                            ProductName = "Classic Gold Watch",
                            PromotionPrice = 3200000m,
                            Quantity = 15,
                            SeoTitle = "classic-gold-watch",
                            ShopID = 1,
                            Status = true,
                            VAT = true,
                            ViewCount = 0
                        },
                        new
                        {
                            ProductID = 6,
                            BrandID = 1,
                            CateID = 8,
                            CreatedDate = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Detail = "Breathable mesh upper",
                            Hot = true,
                            Image = "anh4sanpham.jpg",
                            ListImages = "nike1.jpg,nike2.jpg",
                            MetaDescription = "nike air max",
                            MetaKeywords = "nike, shoes",
                            Price = 3500000m,
                            ProductDescription = "Advanced cushioning for daily comfort.",
                            ProductName = "Nike Air Max 270",
                            PromotionPrice = 3200000m,
                            Quantity = 40,
                            SeoTitle = "nike-air-max-270",
                            ShopID = 1,
                            Status = true,
                            VAT = true,
                            ViewCount = 0
                        },
                        new
                        {
                            ProductID = 7,
                            BrandID = 2,
                            CateID = 8,
                            CreatedDate = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Detail = "Primeknit upper",
                            Hot = true,
                            Image = "anh5sanpham.jpg",
                            ListImages = "adi1.jpg,adi2.jpg",
                            MetaDescription = "adidas ultraboost",
                            MetaKeywords = "adidas, running",
                            Price = 4200000m,
                            ProductDescription = "Ultimate energy return for runners.",
                            ProductName = "Adidas Ultraboost 22",
                            PromotionPrice = 3800000m,
                            Quantity = 35,
                            SeoTitle = "adidas-ultraboost-22",
                            ShopID = 1,
                            Status = true,
                            VAT = true,
                            ViewCount = 0
                        },
                        new
                        {
                            ProductID = 8,
                            BrandID = 3,
                            CateID = 4,
                            CreatedDate = new DateTime(2026, 4, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Detail = "Airism technology",
                            Hot = false,
                            Image = "anh6sanpham.jpg",
                            ListImages = "uni1.jpg",
                            MetaDescription = "airism shirt",
                            MetaKeywords = "uniqlo, t-shirt",
                            Price = 350000m,
                            ProductDescription = "Smooth and quick-drying fabric.",
                            ProductName = "Uniqlo Airism T-Shirt",
                            PromotionPrice = 299000m,
                            Quantity = 200,
                            SeoTitle = "uniqlo-airism-tshirt",
                            ShopID = 1,
                            Status = true,
                            VAT = true,
                            ViewCount = 0
                        },
                        new
                        {
                            ProductID = 9,
                            BrandID = 4,
                            CateID = 4,
                            CreatedDate = new DateTime(2026, 4, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Detail = "Premium wool blend",
                            Hot = true,
                            Image = "anh7sanpham.jpg",
                            ListImages = "zara1.jpg",
                            MetaDescription = "slim fit suit",
                            MetaKeywords = "zara, suit",
                            Price = 2500000m,
                            ProductDescription = "Modern slim fit for formal events.",
                            ProductName = "Zara Slim Fit Suit",
                            PromotionPrice = 2100000m,
                            Quantity = 20,
                            SeoTitle = "zara-slim-suit",
                            ShopID = 1,
                            Status = true,
                            VAT = true,
                            ViewCount = 0
                        },
                        new
                        {
                            ProductID = 10,
                            BrandID = 5,
                            CateID = 4,
                            CreatedDate = new DateTime(2026, 4, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Detail = "100% Cotton denim",
                            Hot = false,
                            Image = "anh8sanpham.jpg",
                            ListImages = "hm1.jpg",
                            MetaDescription = "denim jacket",
                            MetaKeywords = "hm, denim",
                            Price = 900000m,
                            ProductDescription = "Classic denim jacket with a modern twist.",
                            ProductName = "H&M Denim Jacket",
                            PromotionPrice = 750000m,
                            Quantity = 60,
                            SeoTitle = "hm-denim-jacket",
                            ShopID = 1,
                            Status = true,
                            VAT = true,
                            ViewCount = 0
                        },
                        new
                        {
                            ProductID = 11,
                            BrandID = 1,
                            CateID = 5,
                            CreatedDate = new DateTime(2026, 4, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Detail = "Tech fleece fabric",
                            Hot = true,
                            Image = "anh9sanpham.jpg",
                            ListImages = "nike3.jpg",
                            MetaDescription = "nike tech fleece",
                            MetaKeywords = "nike, fleece",
                            Price = 2200000m,
                            ProductDescription = "Lightweight warmth for cold days.",
                            ProductName = "Nike Tech Fleece",
                            PromotionPrice = 1900000m,
                            Quantity = 45,
                            SeoTitle = "nike-tech-fleece",
                            ShopID = 1,
                            Status = true,
                            VAT = true,
                            ViewCount = 0
                        },
                        new
                        {
                            ProductID = 12,
                            BrandID = 2,
                            CateID = 4,
                            CreatedDate = new DateTime(2026, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Detail = "French terry cotton",
                            Hot = false,
                            Image = "anh10sanpham.jpg",
                            ListImages = "adi3.jpg",
                            MetaDescription = "adidas originals",
                            MetaKeywords = "adidas, hoodie",
                            Price = 1500000m,
                            ProductDescription = "Iconic style with cozy comfort.",
                            ProductName = "Adidas Originals Hoodie",
                            PromotionPrice = 1200000m,
                            Quantity = 70,
                            SeoTitle = "adidas-hoodie",
                            ShopID = 1,
                            Status = true,
                            VAT = true,
                            ViewCount = 0
                        },
                        new
                        {
                            ProductID = 13,
                            BrandID = 3,
                            CateID = 5,
                            CreatedDate = new DateTime(2026, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Detail = "Slim straight cut",
                            Hot = true,
                            Image = "anh11sanpham.jpg",
                            ListImages = "uni2.jpg",
                            MetaDescription = "selvedge denim",
                            MetaKeywords = "uniqlo, jeans",
                            Price = 1200000m,
                            ProductDescription = "Authentic selvedge denim.",
                            ProductName = "Uniqlo Selvedge Jeans",
                            PromotionPrice = 999000m,
                            Quantity = 90,
                            SeoTitle = "uniqlo-jeans",
                            ShopID = 1,
                            Status = true,
                            VAT = true,
                            ViewCount = 0
                        },
                        new
                        {
                            ProductID = 14,
                            BrandID = 4,
                            CateID = 6,
                            CreatedDate = new DateTime(2026, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Detail = "Lightweight fabric",
                            Hot = false,
                            Image = "anh12sanpham.jpg",
                            ListImages = "zara2.jpg",
                            MetaDescription = "floral skirt",
                            MetaKeywords = "zara, skirt",
                            Price = 800000m,
                            ProductDescription = "Beautiful floral pattern for spring.",
                            ProductName = "Zara Floral Skirt",
                            PromotionPrice = 650000m,
                            Quantity = 55,
                            SeoTitle = "zara-floral-skirt",
                            ShopID = 1,
                            Status = true,
                            VAT = true,
                            ViewCount = 0
                        },
                        new
                        {
                            ProductID = 15,
                            BrandID = 5,
                            CateID = 4,
                            CreatedDate = new DateTime(2026, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Detail = "Soft brushed inside",
                            Hot = false,
                            Image = "anh13sanpham.jpg",
                            ListImages = "hm2.jpg",
                            MetaDescription = "oversized top",
                            MetaKeywords = "hm, sweatshirt",
                            Price = 500000m,
                            ProductDescription = "Relaxed fit for everyday wear.",
                            ProductName = "H&M Oversized Sweatshirt",
                            PromotionPrice = 400000m,
                            Quantity = 120,
                            SeoTitle = "hm-sweatshirt",
                            ShopID = 1,
                            Status = true,
                            VAT = true,
                            ViewCount = 0
                        },
                        new
                        {
                            ProductID = 16,
                            BrandID = 1,
                            CateID = 3,
                            CreatedDate = new DateTime(2026, 4, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Detail = "Padded shoulder straps",
                            Hot = false,
                            Image = "anh14sanpham.jpg",
                            ListImages = "nike4.jpg",
                            MetaDescription = "nike backpack",
                            MetaKeywords = "nike, bag",
                            Price = 850000m,
                            ProductDescription = "Classic design with ample storage.",
                            ProductName = "Nike Heritage Backpack",
                            PromotionPrice = 700000m,
                            Quantity = 40,
                            SeoTitle = "nike-backpack",
                            ShopID = 1,
                            Status = true,
                            VAT = true,
                            ViewCount = 0
                        },
                        new
                        {
                            ProductID = 17,
                            BrandID = 2,
                            CateID = 8,
                            CreatedDate = new DateTime(2026, 4, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Detail = "Synthetic leather upper",
                            Hot = true,
                            Image = "anh15sanpham.jpg",
                            ListImages = "adi4.jpg",
                            MetaDescription = "stan smith shoes",
                            MetaKeywords = "adidas, sneakers",
                            Price = 2300000m,
                            ProductDescription = "Timeless tennis-inspired sneakers.",
                            ProductName = "Adidas Stan Smith",
                            PromotionPrice = 1950000m,
                            Quantity = 50,
                            SeoTitle = "adidas-stan-smith",
                            ShopID = 1,
                            Status = true,
                            VAT = true,
                            ViewCount = 0
                        },
                        new
                        {
                            ProductID = 18,
                            BrandID = 3,
                            CateID = 5,
                            CreatedDate = new DateTime(2026, 4, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Detail = "Heattech technology",
                            Hot = false,
                            Image = "anh16sanpham.jpg",
                            ListImages = "uni3.jpg",
                            MetaDescription = "thermal wear",
                            MetaKeywords = "uniqlo, leggings",
                            Price = 450000m,
                            ProductDescription = "Thermal leggings for winter warmth.",
                            ProductName = "Uniqlo Heattech Leggings",
                            PromotionPrice = 350000m,
                            Quantity = 150,
                            SeoTitle = "uniqlo-heattech",
                            ShopID = 1,
                            Status = true,
                            VAT = true,
                            ViewCount = 0
                        },
                        new
                        {
                            ProductID = 19,
                            BrandID = 4,
                            CateID = 3,
                            CreatedDate = new DateTime(2026, 4, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Detail = "Metallic buckle",
                            Hot = false,
                            Image = "anh17sanpham.jpg",
                            ListImages = "zara3.jpg",
                            MetaDescription = "leather belt",
                            MetaKeywords = "zara, belt",
                            Price = 600000m,
                            ProductDescription = "100% genuine leather belt.",
                            ProductName = "Zara Leather Belt",
                            PromotionPrice = 450000m,
                            Quantity = 100,
                            SeoTitle = "zara-belt",
                            ShopID = 1,
                            Status = true,
                            VAT = true,
                            ViewCount = 0
                        },
                        new
                        {
                            ProductID = 20,
                            BrandID = 5,
                            CateID = 4,
                            CreatedDate = new DateTime(2026, 4, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Detail = "Cotton and elastane",
                            Hot = false,
                            Image = "anh18sanpham.jpg",
                            ListImages = "hm3.jpg",
                            MetaDescription = "tank top",
                            MetaKeywords = "hm, top",
                            Price = 250000m,
                            ProductDescription = "Simple and stylish ribbed top.",
                            ProductName = "H&M Ribbed Tank Top",
                            PromotionPrice = 180000m,
                            Quantity = 180,
                            SeoTitle = "hm-tank-top",
                            ShopID = 1,
                            Status = true,
                            VAT = true,
                            ViewCount = 0
                        },
                        new
                        {
                            ProductID = 21,
                            BrandID = 1,
                            CateID = 5,
                            CreatedDate = new DateTime(2026, 4, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Detail = "Sweat-wicking fabric",
                            Hot = true,
                            Image = "anh19sanpham.jpg",
                            ListImages = "nike5.jpg",
                            MetaDescription = "sport shorts",
                            MetaKeywords = "nike, shorts",
                            Price = 750000m,
                            ProductDescription = "Stay dry during your workout.",
                            ProductName = "Nike Dri-FIT Shorts",
                            PromotionPrice = 600000m,
                            Quantity = 85,
                            SeoTitle = "nike-shorts",
                            ShopID = 1,
                            Status = true,
                            VAT = true,
                            ViewCount = 0
                        },
                        new
                        {
                            ProductID = 22,
                            BrandID = 2,
                            CateID = 3,
                            CreatedDate = new DateTime(2026, 4, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Detail = "Adjustable strap",
                            Hot = false,
                            Image = "anh20sanpham.jpg",
                            ListImages = "adi5.jpg",
                            MetaDescription = "baseball cap",
                            MetaKeywords = "adidas, cap",
                            Price = 450000m,
                            ProductDescription = "Classic 6-panel cap.",
                            ProductName = "Adidas Baseball Cap",
                            PromotionPrice = 350000m,
                            Quantity = 110,
                            SeoTitle = "adidas-cap",
                            ShopID = 1,
                            Status = true,
                            VAT = true,
                            ViewCount = 0
                        },
                        new
                        {
                            ProductID = 23,
                            BrandID = 3,
                            CateID = 4,
                            CreatedDate = new DateTime(2026, 4, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Detail = "Linen cotton blend",
                            Hot = true,
                            Image = "anh21sanpham.jpg",
                            ListImages = "uni4.jpg",
                            MetaDescription = "linen shirt",
                            MetaKeywords = "uniqlo, shirt",
                            Price = 750000m,
                            ProductDescription = "Cool and breathable linen shirt.",
                            ProductName = "Uniqlo Linen Shirt",
                            PromotionPrice = 599000m,
                            Quantity = 65,
                            SeoTitle = "uniqlo-linen-shirt",
                            ShopID = 1,
                            Status = true,
                            VAT = true,
                            ViewCount = 0
                        },
                        new
                        {
                            ProductID = 24,
                            BrandID = 4,
                            CateID = 5,
                            CreatedDate = new DateTime(2026, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Detail = "Flowy material",
                            Hot = true,
                            Image = "anh22sanpham.jpg",
                            ListImages = "zara4.jpg",
                            MetaDescription = "wide leg",
                            MetaKeywords = "zara, trousers",
                            Price = 1300000m,
                            ProductDescription = "High-waisted wide leg pants.",
                            ProductName = "Zara Wide Leg Trousers",
                            PromotionPrice = 1100000m,
                            Quantity = 45,
                            SeoTitle = "zara-trousers",
                            ShopID = 1,
                            Status = true,
                            VAT = true,
                            ViewCount = 0
                        },
                        new
                        {
                            ProductID = 25,
                            BrandID = 5,
                            CateID = 4,
                            CreatedDate = new DateTime(2026, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Detail = "Soft wool blend",
                            Hot = true,
                            Image = "anh23sanpham.jpg",
                            ListImages = "hm4.jpg",
                            MetaDescription = "winter coat",
                            MetaKeywords = "hm, coat",
                            Price = 2800000m,
                            ProductDescription = "Stay warm and stylish in winter.",
                            ProductName = "H&M Wool Blend Coat",
                            PromotionPrice = 2400000m,
                            Quantity = 15,
                            SeoTitle = "hm-wool-coat",
                            ShopID = 1,
                            Status = true,
                            VAT = true,
                            ViewCount = 0
                        });
                });

            modelBuilder.Entity("FinalProject.Models.ProductCategory", b =>
                {
                    b.Property<int>("CateID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CateID"));

                    b.Property<string>("CateName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("MetaDescription")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MetaKeywords")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("ParentID")
                        .HasColumnType("int");

                    b.Property<string>("SeoTitle")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int?>("Sort")
                        .HasColumnType("int");

                    b.Property<bool>("Statuss")
                        .HasColumnType("bit");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("CateID");

                    b.HasIndex("ParentID");

                    b.ToTable("tb_ProductCategory");

                    b.HasData(
                        new
                        {
                            CateID = 1,
                            CateName = "Men's Fashion",
                            CreatedDate = new DateTime(2026, 3, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MetaDescription = "High quality clothing for men",
                            MetaKeywords = "men clothing, fashion",
                            SeoTitle = "mens-fashion",
                            Sort = 1,
                            Statuss = true
                        },
                        new
                        {
                            CateID = 2,
                            CateName = "Women's Fashion",
                            CreatedDate = new DateTime(2026, 3, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MetaDescription = "Latest fashion trends for women",
                            MetaKeywords = "dresses, women fashion",
                            SeoTitle = "womens-fashion",
                            Sort = 2,
                            Statuss = true
                        },
                        new
                        {
                            CateID = 3,
                            CateName = "Accessories",
                            CreatedDate = new DateTime(2026, 3, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MetaDescription = "Fashion accessories for everyone",
                            MetaKeywords = "bags, watches, jewelry",
                            SeoTitle = "accessories",
                            Sort = 3,
                            Statuss = true
                        },
                        new
                        {
                            CateID = 4,
                            CateName = "Men's Torso",
                            CreatedDate = new DateTime(2026, 3, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MetaDescription = "Stylish shirts for men",
                            MetaKeywords = "t-shirts, polo",
                            ParentID = 1,
                            SeoTitle = "mens-torso",
                            Sort = 1,
                            Statuss = true
                        },
                        new
                        {
                            CateID = 5,
                            CateName = "Men's Leggings",
                            CreatedDate = new DateTime(2026, 3, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MetaDescription = "Comfortable pants for men",
                            MetaKeywords = "jeans, trousers",
                            ParentID = 1,
                            SeoTitle = "mens-leggings",
                            Sort = 2,
                            Statuss = true
                        },
                        new
                        {
                            CateID = 6,
                            CateName = "Dresses & Skirts",
                            CreatedDate = new DateTime(2026, 3, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MetaDescription = "Beautiful dresses for ladies",
                            MetaKeywords = "maxi dress, skirts",
                            ParentID = 2,
                            SeoTitle = "dresses-skirts",
                            Sort = 1,
                            Statuss = true
                        },
                        new
                        {
                            CateID = 7,
                            CateName = "Women's Handbags",
                            CreatedDate = new DateTime(2026, 3, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MetaDescription = "Luxury handbags for women",
                            MetaKeywords = "purses, totes",
                            ParentID = 2,
                            SeoTitle = "womens-handbags",
                            Sort = 2,
                            Statuss = true
                        },
                        new
                        {
                            CateID = 8,
                            CateName = "Footwear",
                            CreatedDate = new DateTime(2026, 3, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MetaDescription = "Quality footwear for all ages",
                            MetaKeywords = "shoes, sneakers",
                            ParentID = 3,
                            SeoTitle = "footwear",
                            Sort = 1,
                            Statuss = true
                        },
                        new
                        {
                            CateID = 9,
                            CateName = "Watches & Jewelry",
                            CreatedDate = new DateTime(2026, 3, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MetaDescription = "Premium timepieces and jewelry",
                            MetaKeywords = "gold, luxury watches",
                            ParentID = 3,
                            SeoTitle = "watches-jewelry",
                            Sort = 2,
                            Statuss = true
                        });
                });

            modelBuilder.Entity("FinalProject.Models.Promotion", b =>
                {
                    b.Property<int>("PromotionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PromotionID"));

                    b.Property<int>("DiscountPercent")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("PromotionID");

                    b.ToTable("tb_Promotion");
                });

            modelBuilder.Entity("FinalProject.Models.Shop", b =>
                {
                    b.Property<int>("ShopID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShopID"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ContactPhone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CoverImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsBanned")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("OwnerId")
                        .HasColumnType("int");

                    b.Property<decimal>("RatingAverage")
                        .HasColumnType("decimal(3,2)");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("ShopAddress")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ShopDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShopName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TotalFollowers")
                        .HasColumnType("int");

                    b.Property<int>("TotalProducts")
                        .HasColumnType("int");

                    b.Property<int>("TotalReviews")
                        .HasColumnType("int");

                    b.Property<int>("TotalSold")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ShopID");

                    b.HasIndex("OwnerId")
                        .IsUnique()
                        .HasFilter("[OwnerId] IS NOT NULL");

                    b.HasIndex("RoleId");

                    b.ToTable("tb_Shop", (string)null);

                    b.HasData(
                        new
                        {
                            ShopID = 1,
                            City = "Ho Chi Minh City",
                            ContactEmail = "support@urbanchic.com",
                            ContactPhone = "+84987654321",
                            Country = "Vietnam",
                            CoverImageUrl = "cover-urban.jpg",
                            CreatedAt = new DateTime(2026, 3, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsBanned = false,
                            IsVerified = true,
                            LogoUrl = "logo-urban.png",
                            RatingAverage = 4.80m,
                            RoleId = 2,
                            ShopAddress = "123 ABC Street, District 1",
                            ShopDescription = "Premium streetwear and modern fashion trends for the young generation.",
                            ShopName = "Urban Chic Fashion",
                            TotalFollowers = 1200,
                            TotalProducts = 50,
                            TotalReviews = 450,
                            TotalSold = 2500
                        });
                });

            modelBuilder.Entity("FinalProject.Models.ShopReview", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReviewId"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("ReviewerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ShopId")
                        .HasColumnType("int");

                    b.HasKey("ReviewId");

                    b.HasIndex("ShopId");

                    b.ToTable("tb_ShopReview");
                });

            modelBuilder.Entity("FinalProject.Models.SystemLog", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogId"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LogId");

                    b.HasIndex("UserId");

                    b.ToTable("tb_SystemLog");
                });

            modelBuilder.Entity("FinalProject.Models.SystemSetting", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("MaintenanceMode")
                        .HasColumnType("bit");

                    b.Property<decimal>("ShippingFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SiteName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("tb_SystemSetting");
                });

            modelBuilder.Entity("FinalProject.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("EmailVerified")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsBanned")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("PhoneVerified")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("tb_Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "881370c9-277a-49c8-914c-8ad53940efa7",
                            CreatedAt = new DateTime(2026, 3, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@fashionstore.com",
                            EmailConfirmed = true,
                            EmailVerified = false,
                            FullName = "System Administrator",
                            IsActive = true,
                            IsBanned = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@FASHIONSTORE.COM",
                            NormalizedUserName = "ADMIN@FASHIONSTORE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEH25h7ZQvQE8hOwTaBbjOB32HV7wnHtkWSfxmcVzInrNEyS3y96uH2cNkm9/UPRG1A==",
                            PhoneNumberConfirmed = false,
                            PhoneVerified = false,
                            SecurityStamp = "23e669af-337e-4e6a-910b-8f6801457c72",
                            TwoFactorEnabled = false,
                            UserName = "admin@fashionstore.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("tb_Roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConcurrencyStamp = "ef13c806-04c4-49cf-bc8c-db22786294d4",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = 2,
                            ConcurrencyStamp = "05dfec67-bfca-4f86-afb4-768728a5d7b7",
                            Name = "User",
                            NormalizedName = "USER"
                        },
                        new
                        {
                            Id = 3,
                            ConcurrencyStamp = "4845c675-36ee-46c8-8fe3-091fb3126fa2",
                            Name = "Shop",
                            NormalizedName = "SHOP"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("tb_RoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("tb_UserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("tb_UserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("tb_UserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            RoleId = 1
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("tb_UserTokens", (string)null);
                });

            modelBuilder.Entity("FinalProject.Models.CartItems", b =>
                {
                    b.HasOne("FinalProject.Models.Carts", "Cart")
                        .WithMany("CartItems")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FinalProject.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("FinalProject.Models.Carts", b =>
                {
                    b.HasOne("FinalProject.Models.User", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("FinalProject.Models.Order", b =>
                {
                    b.HasOne("FinalProject.Models.User", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("FinalProject.Models.OrderDetails", b =>
                {
                    b.HasOne("FinalProject.Models.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId");

                    b.HasOne("FinalProject.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId");

                    b.HasOne("FinalProject.Models.Shop", "Shop")
                        .WithMany()
                        .HasForeignKey("ShopId");

                    b.Navigation("Order");

                    b.Navigation("Product");

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("FinalProject.Models.Product", b =>
                {
                    b.HasOne("FinalProject.Models.Brand", "Brand")
                        .WithMany("Products")
                        .HasForeignKey("BrandID");

                    b.HasOne("FinalProject.Models.ProductCategory", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CateID");

                    b.HasOne("FinalProject.Models.Promotion", "Promotion")
                        .WithMany()
                        .HasForeignKey("PromotionId");

                    b.HasOne("FinalProject.Models.Shop", "Shop")
                        .WithMany()
                        .HasForeignKey("ShopID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("Category");

                    b.Navigation("Promotion");

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("FinalProject.Models.ProductCategory", b =>
                {
                    b.HasOne("FinalProject.Models.ProductCategory", "ParentCategory")
                        .WithMany("ChildCategories")
                        .HasForeignKey("ParentID");

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("FinalProject.Models.Shop", b =>
                {
                    b.HasOne("FinalProject.Models.User", "Owner")
                        .WithOne("MyShop")
                        .HasForeignKey("FinalProject.Models.Shop", "OwnerId");

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Owner");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("FinalProject.Models.ShopReview", b =>
                {
                    b.HasOne("FinalProject.Models.Shop", "Shop")
                        .WithMany()
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("FinalProject.Models.SystemLog", b =>
                {
                    b.HasOne("FinalProject.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("FinalProject.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("FinalProject.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("FinalProject.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("FinalProject.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FinalProject.Models.Brand", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("FinalProject.Models.Carts", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("FinalProject.Models.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("FinalProject.Models.ProductCategory", b =>
                {
                    b.Navigation("ChildCategories");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("FinalProject.Models.User", b =>
                {
                    b.Navigation("MyShop")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
